/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subscribeEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Overview: {
            /** Format: date-time */
            generatedAt: string;
            environment: string;
            connection: string;
            kpis: components["schemas"]["KPI"][];
            tokenTrend: components["schemas"]["DailyUsage"][];
            modelUsage: components["schemas"]["ModelUsage"][];
            quotaSignals: components["schemas"]["QuotaSignal"][];
            accounts: components["schemas"]["AccountSummary"][];
            alerts: components["schemas"]["Alert"][];
        };
        KPI: {
            id: string;
            label: string;
            value: number;
            unit: string;
            delta: number;
            tone: string;
        };
        DailyUsage: {
            /** Format: date */
            date: string;
            /** Format: int64 */
            inputTokens: number;
            /** Format: int64 */
            outputTokens: number;
            /** Format: int64 */
            cacheTokens: number;
            /** Format: int64 */
            requests: number;
        };
        ModelUsage: {
            model: string;
            /** Format: int64 */
            tokens: number;
            color: string;
        };
        QuotaSignal: {
            id: string;
            provider: string;
            label: string;
            /** @enum {string} */
            kind: "credits" | "balance" | "rate_window" | "token_plan";
            value: number;
            total?: number;
            unit: string;
            remainingPercent?: number;
            /** Format: date-time */
            resetAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** @enum {string} */
            status: "healthy" | "warning" | "critical";
            source: string;
            confidence: string;
        };
        AccountSummary: {
            id: string;
            provider: string;
            region: string;
            alias: string;
            services: string[];
            primaryMetric: string;
            secondaryMetric: string;
            status: string;
            source: string;
            /** Format: date-time */
            lastRefreshedAt: string;
            /** Format: date-time */
            nextRefreshAt: string;
            error?: string;
        };
        Alert: {
            id: string;
            severity: string;
            title: string;
            message: string;
            provider: string;
            /** Format: date-time */
            createdAt: string;
            recovery: string;
        };
        Provider: {
            id: string;
            name: string;
            region: string;
            tier: string;
            status: string;
            authMethods: string[];
            capabilities: string[];
            accountCount: number;
            /** Format: date-time */
            lastCheckedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current monitoring overview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider adapter status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Provider"][];
                    };
                };
            };
        };
    };
    refreshAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refresh completed for the v0.1 synthetic adapters */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    subscribeEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
