/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{providerID}/accounts/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importProviderCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{providerID}/accounts/secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["connectProviderSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{providerID}/accounts/custom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["connectCustomQuotaEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{providerID}/oauth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startProviderOAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{providerID}/oauth/{sessionID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProviderOAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/codex/accounts/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importCodexAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/codex/device-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startCodexDeviceLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/codex/device-login/{sessionID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCodexDeviceLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountID}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subscribeEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Overview: {
            /** Format: date-time */
            generatedAt: string;
            environment: string;
            connection: string;
            kpis: components["schemas"]["KPI"][];
            tokenTrend: components["schemas"]["DailyUsage"][];
            modelUsage: components["schemas"]["ModelUsage"][];
            quotaSignals: components["schemas"]["QuotaSignal"][];
            accounts: components["schemas"]["AccountSummary"][];
            alerts: components["schemas"]["Alert"][];
        };
        KPI: {
            id: string;
            label: string;
            value: number;
            unit: string;
            delta: number;
            tone: string;
        };
        DailyUsage: {
            /** Format: date */
            date: string;
            /** Format: int64 */
            inputTokens: number;
            /** Format: int64 */
            outputTokens: number;
            /** Format: int64 */
            cacheTokens: number;
            /** Format: int64 */
            requests: number;
        };
        ModelUsage: {
            model: string;
            /** Format: int64 */
            tokens: number;
            color: string;
        };
        QuotaSignal: {
            id: string;
            provider: string;
            label: string;
            /** @enum {string} */
            kind: "quota" | "credits" | "balance" | "rate_window" | "token_plan";
            value: number;
            total?: number;
            unit: string;
            remainingPercent?: number;
            /** Format: int64 */
            windowSeconds?: number;
            /** Format: date-time */
            resetAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** @enum {string} */
            status: "healthy" | "warning" | "critical";
            source: string;
            confidence: string;
        };
        AccountSummary: {
            id: string;
            providerId: string;
            provider: string;
            region: string;
            alias: string;
            services: string[];
            primaryMetric: string;
            secondaryMetric: string;
            status: string;
            source: string;
            /** Format: date-time */
            lastRefreshedAt: string;
            /** Format: date-time */
            nextRefreshAt: string;
            error?: string;
            email?: string;
            plan?: string;
            authMethod?: string;
            synthetic: boolean;
            quotaWindows: components["schemas"]["QuotaSignal"][];
        };
        Alert: {
            id: string;
            severity: string;
            title: string;
            message: string;
            provider: string;
            /** Format: date-time */
            createdAt: string;
            recovery: string;
        };
        Provider: {
            id: string;
            name: string;
            region: string;
            tier: string;
            status: string;
            authMethods: string[];
            capabilities: string[];
            accountCount: number;
            /** Format: date-time */
            lastCheckedAt: string;
            description: string;
            category: string;
            liveAuth: boolean;
        };
        DeviceLoginSession: {
            id: string;
            provider: string;
            /** @enum {string} */
            status: "pending" | "completed" | "failed";
            userCode?: string;
            /** Format: uri */
            verifyUrl: string;
            /** Format: date-time */
            expiresAt: string;
            accountId?: string;
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current monitoring overview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider adapter status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Provider"][];
                    };
                };
            };
        };
    };
    refreshAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refresh completed for connected real accounts */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    importProviderCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    alias?: string;
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Credential imported and live quota fetched */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummary"];
                };
            };
        };
    };
    connectProviderSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    alias?: string;
                    secret: string;
                };
            };
        };
        responses: {
            /** @description Secret verified and live quota fetched */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummary"];
                };
            };
        };
    };
    connectCustomQuotaEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    alias?: string;
                    /** Format: uri */
                    endpoint: string;
                    /** @enum {string} */
                    method: "GET" | "POST";
                    /** @enum {string} */
                    authType: "bearer" | "header" | "cookie" | "none";
                    headerName?: string;
                    headerPrefix?: string;
                    secret?: string;
                    requestBody?: string;
                    valuePath: string;
                    totalPath?: string;
                    resetAtPath?: string;
                    expiresAtPath?: string;
                    label: string;
                    unit: string;
                    kind: string;
                };
            };
        };
        responses: {
            /** @description Endpoint authenticated, response mapping verified, and account saved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummary"];
                };
            };
        };
    };
    startProviderOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerID: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    alias?: string;
                };
            };
        };
        responses: {
            /** @description Official provider OAuth login started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceLoginSession"];
                };
            };
        };
    };
    getProviderOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerID: string;
                sessionID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OAuth login status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceLoginSession"];
                };
            };
        };
    };
    importCodexAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    alias?: string;
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Codex account imported and quota fetched */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummary"];
                };
            };
        };
    };
    startCodexDeviceLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    alias?: string;
                };
            };
        };
        responses: {
            /** @description Official Codex device login started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceLoginSession"];
                };
            };
        };
    };
    getCodexDeviceLogin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device login status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceLoginSession"];
                };
            };
        };
    };
    refreshAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refreshed account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummary"];
                };
            };
        };
    };
    subscribeEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
